spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/Quotka?serverTimezone=Asia/Seoul
    username: root
    password: sarah1106

    jpa:
      open-in-view: true
      hibernate:
        ddl-auto: create
        use-new-id-generate-mappings: false
      show-sql: true
      properties:
        hibernate.format_sql: true

    thymeleaf:
      cache: false

      main:
        allow-bean-definition-overriding: true
